GlossaryPageContent('<?xml version="1.0" encoding="utf-8"?>\
     <glossaryPopupItem>\
	 <item>\
	  <title><![CDATA[true]]></title>\
	   <description><![CDATA[true]]></description>\
	 </item>\
	 <item>\
	  <title><![CDATA[true]]></title>\
	   <description><![CDATA[true]]></description>\
	 </item>\
	 <item>\
	  <title><![CDATA[true]]></title>\
	   <description><![CDATA[true]]></description>\
	 </item>\
	 <item>\
	  <title><![CDATA[true]]></title>\
	   <description><![CDATA[true]]></description>\
	 </item>\
	 <item>\
	  <title><![CDATA[true]]></title>\
	   <description><![CDATA[true]]></description>\
	 </item>\
	</glossaryPopupItem>')