landingPageContent('<?xml version="1.0" encoding="UTF-8"?>\
<personal_info>\
	<resources><![CDATA[]]></resources>\
	<transcript><![CDATA[<p>There is no transcript in this activity.</p>]]></transcript>\
	<PageContent>\
				<heading><![CDATA[Page title goes here (Tab Activity type 1)<br><br>]]></heading>\
				<paragraph><![CDATA[Fusce a congue mauris Proin utFusce a congue mauris Proin utFusce a congue mauris Proin utFusce a congue mauris Proin ut <span class="ost-text01_txt_color">dolor</span> scelerisque, Fusce a congue mauris Proin ut wwwe wewe we<br><br>]]></paragraph>\
				<instructionText><![CDATA[Click on the icon to learn the deceptive methods of each scheme.<br><br>]]></instructionText>\
   </PageContent>\
    <TabContainer>\
	<tabsize width="275" height="124"></tabsize>\
		<tab>\
			<imageNormal altText="This is a lady">./global_files/templates/tabActivity_screen_type1/images/single_millennials_normal.png</imageNormal>\			<imageVisited>./global_files/templates/tabActivity_screen_type1/images/single_millennials_visited.png</imageVisited>\
			<imageHover>./global_files/templates/tabActivity_screen_type1/images/single_millennials_hover.png</imageHover>\
			<caption><![CDATA[Page title 01 ]]></caption>\
		</tab>\
		<tab>\
			<imageNormal altText="This is a lady">./global_files/templates/tabActivity_screen_type1/images/young_couples_normal.png</imageNormal>\
			<imageVisited>./global_files/templates/tabActivity_screen_type1/images/young_couples_visited.png</imageVisited>\
			<imageHover>./global_files/templates/tabActivity_screen_type1/images/young_couples_hover.png</imageHover>\
			<caption><![CDATA[Page title 02 ]]></caption>\
		</tab>\
		<tab>\
			<imageNormal altText="This is a lady">./global_files/templates/tabActivity_screen_type1/images/young_parents_normal.png</imageNormal>\
			<imageVisited>./global_files/templates/tabActivity_screen_type1/images/young_parents_visited.png</imageVisited>\
			<imageHover>./global_files/templates/tabActivity_screen_type1/images/young_parents_hover.png</imageHover>\
			<caption><![CDATA[Page title 03 ]]></caption>\
		</tab>\
		<!--<tab >\
			<imageNormal altText="This is a lady">./global_files/templates/tabActivity_screen_type1/images/btn3normal.png</imageNormal>\
			<imageVisited>./global_files/templates/tabActivity_screen_type1/images/btn3clicked.png</imageVisited>\
			<hotspot><![CDATA[SINGLE MILLENNIALS]]></hotspot>\
		</tab>-->\
	</TabContainer>	\
	<TabPopupSize width="820" height="214"></TabPopupSize>\
	<popup_container>\
		<para_content><![CDATA[ <div><p> 01 I understand your hesitation around the price. As a consumer myself, I have to work to stay within a set budget.</p>I understand your hesitation around the price. As a consumer myself, I have to work to stay within a set budget.01 I understand your hesitation around the price. As a consumer myself, I have to work to stay within a set budget.</p>I understand your hesitation around the price. As a consumer myself, I have to work to stay within a set budget.</div>]]></para_content>		\
	</popup_container>\
	<popup_container >\
		<para_content><![CDATA[<p>02 I understand your hesitation around the price. As a consumer myself, I have to work to stay within a set budget.</p>I understand your hesitation around the price. As a consumer myself, I have to work to stay within a set budget.]]></para_content>\
	</popup_container>\
	<popup_container >\
		<para_content><![CDATA[<p> 03 I understand your hesitation around the price. As a consumer myself, I have to work to stay within a set budget.</p>I understand your hesitation around the price. As a consumer myself, I have to work to stay within a set budget.]]></para_content>\
	</popup_container>\
	<popup_container >\
		<para_content><![CDATA[<p> 04 I understand your hesitation around the price. As a consumer myself, I have to work to stay within a set budget.</p>I understand your hesitation around the price. As a consumer myself, I have to work to stay within a set budget.]]></para_content>\
	</popup_container>\
	<popup_container >\
		<para_content><![CDATA[<p>I understand your hesitation around the price. As a consumer myself, I have to work to stay within a set budget.</p>I understand your hesitation around the price. As a consumer myself, I have to work to stay within a set budget.]]></para_content>\
	</popup_container>\
	<popup_container >\
		<para_content><![CDATA[<p>I understand your hesitation around the price. As a consumer myself, I have to work to stay within a set budget.</p>I understand your hesitation around the price. As a consumer myself, I have to work to stay within a set budget.]]></para_content>\
	</popup_container >\
	<instruction_close>	\
		<para_content><![CDATA[Click X to close.]]></para_content>\
	</instruction_close>\
</personal_info>')